# Generated by Django 3.0.7 on 2020-06-20 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workrecord', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodel',
            name='workEndTime',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='workStartTime',
            field=models.TimeField(),
        ),
    ]
